#!/usr/bin/env python3

from argparse import ArgumentError
import sys
from math import *
from std_msgs.msg import UInt8
import rospy
import actionlib
from actionlib_msgs.msg import GoalStatus

from geometry_msgs.msg import Point, PoseStamped

from nav_msgs.msg import Path

from spar_msgs.msg import FlightMotionAction, FlightMotionGoal

# Libraries for interfacing with BreadCrumb
from breadcrumb.srv import RequestPath
from breadcrumb.srv import RequestPathRequest
from vision_msgs.msg import ObjectHypothesisWithPose
import numpy as np



# This is getting a bit more complicated now, so we'll put our information in
# a class to keep track of all of our variables. This is not so much different
# to the previous methods, other than the fact that the class will operate
# within itself.
# i.e. it will have it's own publishers, subscribers, etc., that
# will call it's own functions as callbacks, etc.
class Guidance():
	def __init__(self, waypoints, surveyAltitude):
		self.surveyAltitude = surveyAltitude
		# Make sure we have a valid waypoint list
		# Safe boundary values, default to X<2,Y<2,Z<2.
		self.safeRangeX = rospy.get_param("~safeRangeX", 4)
		self.safeRangeY = rospy.get_param("~safeRangeY", 2.5)
		self.safeRangeZ = rospy.get_param("~safeRangeZ", 4.5) 
		print("Survey Alt: ",self.surveyAltitude)
		if not self.check_waypoints(waypoints):
			raise ArgumentError("Invalid waypoint list input!")

		# Internal counter to see what waypoint were are up to
		self.nextWaypointIndex = 0
		self.waypoint_counter = 0
		self.payload_id = 1

		

		#Aruco storage and landing logic
		#This will be checked to see if the drone has landed, before attempting a land and finishing the mission
		#logical checks for mission objecive completion
		self.completed_payload_1 = False
		self.completed_payload_2 = False
		self.completed_search = False
		self.mission_complete = False
		self.land_staging = False
		self.landed = False #Only triggered True at end of flight
		self.target1 = False
		self.target2 = False

		self.markers = np.full((101, 2), np.nan)
		######## HARD CODED LANDING MARKER ID AND COORDINATES ##########
		self.landing_marker = 4
		self.markers[self.landing_marker,:] = [1.8,1.8]
		

		#Create a publisher for payload commands
		self.pub_payload = rospy.Publisher('payloadcommands', UInt8, queue_size=2)

		# Set a flag to indicate that we are doing a specific inspection
		# and that we are not following our waypoint list
		# This will stop our "waypoint is reached" callback from firing
		# during the roi diversion and taking over our flight!
		self.performing_roi = False

		# Save the input waypoints
		self.waypoints = waypoints
		# Display the full path
		self.display_path(waypoints,"/guidance/fullPath")

		# Make some space to record down our current location
		self.current_location = Point()
		# Set our linear and rotational velocities for the flight
		self.vel_linear = rospy.get_param("~vel_linear", 0.8)
		self.vel_yaw = rospy.get_param("~vel_yaw", 0.8)
		# Set our position and yaw waypoint accuracies
		self.accuracy_pos = rospy.get_param("~acc_pos", 0.1)
		self.accuracy_yaw = rospy.get_param("~acc_yaw", 0.1)
		# Get survey altitude
		self.surveyAltitude = rospy.get_param("~surveyAlt", 1)

		# Create our action client
		action_ns = rospy.get_param("~action_topic", 'spar/flight')
		self.spar_client = actionlib.SimpleActionClient(action_ns, FlightMotionAction)
		rospy.loginfo("Waiting for spar...")
		self.spar_client.wait_for_server()

		# Wait to connect with Breadcrumb (Warning, you code might get stuck in here if breadcrumb is not running)
		# Code will error if you try to connect to a service
		# that does not exist
		
		##########BREADCRUMB DEACTIVATED ####################################################################################
		#rospy.wait_for_service('/breadcrumb/request_path')
		#self.srvc_bc = rospy.ServiceProxy('/breadcrumb/request_path', RequestPath)

		if not rospy.is_shutdown():
			# Good to go, start mission
			rospy.loginfo("Starting waypoint mission")

			# Setup first waypoint segment
			# XXX:	Another option would be to do "takeoff" and leave "nextWaypointIndex = 0" to
			#		begin the mission at the first waypoint after take-off
			rospy.loginfo("Doing first waypoint / maybe takeoff")
			self.send_wp(self.waypoints[0])
			self.nextWaypointIndex += 1
			# Initialisation breadcrumb waypoints
			self.breadcrumbWPSnextIndex = 0
			self.breadcrumbMode = False
			self.breadcrumbWPS = []

			# Setup a timer to check if our waypoint has completed at 20Hz
			rospy.loginfo("Setting callbacks")
			self.timer = rospy.Timer( rospy.Duration(1.0/20.0), self.check_waypoint_status )
			# Callback to save "current location" such that we can perform and return
			# from a diversion to the correct location
			# XXX: These topics could be hard-coded to avoid using a launch file
			self.sub_pose = rospy.Subscriber("~pose", PoseStamped, self.callback_pose)
			# Subscriber to catch "ROI" diversion commands
			self.sub_roi = rospy.Subscriber("target_detection/roi", ObjectHypothesisWithPose, self.callback_detection)

			# XXX: Could have a publisher to output our waypoint progress
			# throughout the flight (should publish each time the waypoint
			# counter is increased). Note: will also need to import "Float32"
			# from "std_msgs.msg" in the header
			# self.pub_progress = rospy.Subscriber("~waypoint_progress", Float32, 10)

			# If shutdown is issued (eg. CTRL+C), cancel current
	 		# mission before rospy is shutdown.
			rospy.loginfo("Running callbacks while not shutdown...")
			rospy.on_shutdown( lambda : self.shutdown() )

	# This function will check if a list of waypoints is in the format we expect
	def check_waypoints(self, wps):
		# Make sure waypoints are a list
		if not isinstance(wps, list):
			rospy.logwarn("Waypoints are not list")
			return False

		# Make sure we have at least one waypoint
		if len(wps) < 1:
			rospy.logwarn("Waypoints list is empty")
			return False

		# Check each of our waypoints
		for i in range(len(wps)):
			if not self.check_waypoint(wps[i]):
				rospy.logwarn("Waypoint %i did not pass check" % (i + 1))
				return False

		# If we haven't returned false yet, then waypoints look good!
		return True


	# This function will check if a waypoint is in the format we expect
	def check_waypoint(self, wp):
		# Make sure each waypoint is a list
		if not isinstance(wp, list):
			rospy.logwarn("Waypoint is not a list of coordinates")
			return False

		# Make sure each waypoint has 4 values
		if len(wp) != 4:
			rospy.logwarn("Waypoint has an invalid length (must be X/Y/Z/Yaw)")
			return False

		# Check if the waypoint is inside the net for X, Y and Z:
		if abs(wp[0]) > self.safeRangeX or abs(wp[1]) > self.safeRangeY or wp[2] > self.safeRangeZ:
			rospy.logwarn("wp values x: {} - y: {} - z {}".format(wp[0], wp[1], wp[2]))
			rospy.logwarn("Waypoint has an invalid size for O134 (must be -{}<X<{}/-{}<Y<{}/Z<{}/Yaw)".format(self.safeRangeX,self.safeRangeX,self.safeRangeY,self.safeRangeY,self.safeRangeZ))
			return False

		# If we haven't returned false yet, then waypoint looks valid!
		return True


	# This function will make sure we shut down the node as safely as possible
	def shutdown(self):
		# Unregister anything that needs it here
		rospy.loginfo("Unregistering topics and shuting down...")
		self.sub_pose.unregister()
		self.sub_roi.unregister()
		self.spar_client.cancel_goal()

		rospy.loginfo("Guidance stopped")


	# This function will check receive the current pose of the UAV constantly
	def callback_pose(self, msg_in):
		# Store the current position at all times so it can be accessed later
		# rospy.loginfo("Updating Pose UAV...")
		self.current_location = msg_in.pose.position


	def callback_detection(self, msg_in):
		self.id = msg_in.id

		if 0 <= self.id <= 100:
			rospy.loginfo("Saving marker coordinates into the array")
			self.marker_storage(msg_in)

		elif self.id == 101:
			if not self.target1:
				self.target1 = True
				rospy.loginfo("Triggering ROI Diversion for Target 1")
				self.inspect_roi(msg_in)

		elif self.id == 102:
			if not self.target2:
				self.target2 = True
				rospy.loginfo("Triggering ROI Diversion for Target 2")
				self.inspect_roi(msg_in)


	def marker_storage(self, msg_in):
		# Extracting the marker coordinates from the message
		self.coordinates = msg_in.pose.pose.position
		
		# Extracting the ArUco marker id number
		self.row = msg_in.id

		# Inserting coordinates into respective row number 
		self.markers[self.row,:] = [self.coordinates.x, self.coordinates.y]



	# This function will fire whenever a ROI pose message is sent
	# It is also responsible for handling the ROI "inspection task"
	def inspect_roi(self, msg_in):
		# Set our flag that we are performing the diversion
		self.performing_roi = True

		# Extracting message data from new message type
		msg_in = msg_in.pose

		rospy.loginfo("Starting diversion to ROI...")
		# Cancel the current goal (if there is one)
		self.spar_client.cancel_goal()
		# Record our current location so we can return to it later
		start_location = self.current_location
		# XXX:	It would also be a good idea to capture "current yaw" from
		#		the pose to maintain that throughout a diversion

		# Set the "diversion waypoint" (at yaw zero)
		# dwp = [msg_in.pose.position.x, msg_in.pose.position.y, msg_in.pose.position.z, 0.0]
		dwp = [msg_in.pose.position.x, msg_in.pose.position.y, self.current_location.z, 0.0]
		# Set the "return waypoint" (at yaw zero)
		rwp = [self.current_location.x, self.current_location.y, self.current_location.z, 0.0]

		# XXX: Could pause here for a moment with ( "rospy.sleep(...)" ) to make sure the UAV stops correctly

		self.send_wp(dwp)
		self.spar_client.wait_for_result()
		if self.spar_client.get_state() != GoalStatus.SUCCEEDED:
			# Something went wrong, cancel out of guidance!
			rospy.signal_shutdown("cancelled")
			return

		rospy.loginfo("Reached diversion ROI!")
		# CODE FOR HOVER AND PAYLOAD DEPLOYMENT

		rospy.sleep(rospy.Duration(6))
		
		#self.payload_id = UInt8()
		self.payload_id = UInt8(self.payload_id)
		rospy.loginfo(f"Sending payload deployment {self.payload_id.data}")
		self.pub_payload.publish(self.payload_id.data)
		# 2 seconds to deploy payload
		# NOTE THIS IS TO BE REPLACED WITH A CONFIRMATION MESSAGE FROM PAYLOAD DEPLOYMENT
		rospy.sleep(rospy.Duration(2))
		rospy.loginfo("Returning to flight plan...")

		self.send_wp(rwp)
		self.spar_client.wait_for_result()
		if self.spar_client.get_state() != GoalStatus.SUCCEEDED:
			# Something went wrong, cancel out of guidance!
			rospy.signal_shutdown("cancelled")
			return

		# "nextWaypointIndex" represents the "next waypoint"
		# "nextWaypointIndex - 1" represents the "current waypoint"
		rospy.loginfo("Resuming flight plan from waypoint %i!" % (self.nextWaypointIndex - 1))
		self.send_wp(self.waypoints[self.nextWaypointIndex - 1])
		# Unset our flag that we are performing a diversion
		# to allow the waypoint timer to take back over
		self.performing_roi = False

	#Aruco marker detection handling
	def detection_aruco(self,msg_in):
		#This function is called by the aruco detection node/topic
		#It will store the detected aruco marker and its position
		#!NOTE !!!!!!position z is being used to store the marker id
		
		#Store the detected marker position in the marker array (row index -1 matches the marker ID)
		self.markers[msg_in.position.z-1,0] = msg_in.pose.position.x
		self.markers[msg_in.position.z-1,1] = msg_in.pose.position.y


	# #Target detection handling ####MAYBE NOT NEEDED - EXISTION ROI DIVERSION MAY BE USED
	# def detection_target(self,msg_in):
	# 	#This function is called by the target detection node/topic
	# 	#It will store the detected aruco marker and its position
	# 	#!NOTE !!!!!!position z is being used to store the target id

	# This function is for convinience to simply send out a new waypoint
	def send_wp(self, wp):
		# Make sure the waypoint is valid before continuing
		if not self.check_waypoint(wp):
			rospy.logwarn("Invalid waypoint, skipped...")
			return False
			# raise ArgumentError("Invalid waypoint input!")

		# Build the flight goal
		goal = FlightMotionGoal()
		goal.motion = FlightMotionGoal.MOTION_GOTO
		goal.position.x = wp[0]
		goal.position.y = wp[1]
		goal.position.z = wp[2]
		goal.yaw = wp[3]
		goal.velocity_vertical = self.vel_linear
		goal.velocity_horizontal = self.vel_linear
		goal.yawrate = self.vel_yaw
		goal.wait_for_convergence = True
		goal.position_radius = self.accuracy_pos
		goal.yaw_range = self.accuracy_yaw

		# For this function, we don't wait in the loop.
		# Instead we just send the waypoint and check up on it later
		# This checking is either with the "self.timer" for waypoints
		# or with direct calls during the ROI diversion
		self.spar_client.send_goal(goal)
		 # If shutdown is issued, cancel current mission before rospy is shutdown
		rospy.on_shutdown(lambda : self.spar_client.cancel_goal())

	

	# This function will fire whenever we recieve a timer event (te) from rospy.Timer()
	# The main purpose is to check if a waypoint has been reached,
	# and if so, send out the next waypoint to continue the mission
	def check_waypoint_status(self, te):
		# # If we're performing the ROI diversion, then don't do
		# # anything here, as this is handled in that function
		# if not self.performing_roi:
		# 	# If the last segment has succeeded.
		# 	# For more complex tasks, it might be necessary to also
		# 	# check if you are in waypoint or breadcrum mode.
		# 	# Hint: really, we should check for other status states
		# 	#		(such as aborted), as there are some states
		# 	#		where we won't recover from, and should just exit
		# 	if self.spar_client.get_state() == GoalStatus.SUCCEEDED:
		# 		rospy.loginfo("Reached waypoint %i!" % (self.nextWaypointIndex))

		# 		# XXX:	Another check could go here to finish the mission early
		# 		#		if "all" inspection tasks have been completed
		# 		#		(Add in another "if" and make the waypoint counter check
		# 		#		 an "elif" check instead.
		# 		#		 i.e. if complete; elif more wps; else wps finished)
		# 		if self.nextWaypointIndex < (len(self.waypoints)):

		# 			if not self.breadcrumbMode:
		# 				# Set up a path request for breadcrumb
		# 				req = RequestPathRequest()
		# 				req.start.x = self.waypoints[self.nextWaypointIndex-1][0] # Get X
		# 				req.start.y = self.waypoints[self.nextWaypointIndex-1][1] # Get Y
		# 				req.start.z = self.waypoints[self.nextWaypointIndex-1][2] # Get Z
		# 				req.end.x = self.waypoints[self.nextWaypointIndex][0]	# Get next X
		# 				req.end.y = self.waypoints[self.nextWaypointIndex][1]	# Get next Y
		# 				req.end.z = self.waypoints[self.nextWaypointIndex][2]	# Get next Z

		# 				res = self.srvc_bc(req)
						
		# 				# Breadcrumb will return a vector of poses if a solution was found
		# 				# If no solution was found (i.e. no solution, or request bad
		# 				# start/end), then breadcrumb returns and empty vector
		# 				# XXX: You could also use res.path_sparse (see breadcrumb docs)
		# 				breadcrumbWPS = []
		# 				if len(res.path_sparse.poses) > 0:
		# 					# Print the path to the screen
		# 					rospy.loginfo("Segment {}-1 to {}:".format(self.nextWaypointIndex,self.nextWaypointIndex))
		# 					rospy.loginfo("[%0.2f;%0.2f;%0.2f] => [%0.2f;%0.2f;%0.2f]",
		# 								req.start.x,req.start.y,req.start.z,
		# 								req.end.x,req.end.y,req.end.z)

		# 					# Loop through the solution returned from breadcrumb
		# 					for i in range(len(res.path_sparse.poses)):
		# 						rospy.loginfo("    [%0.2f;%0.2f;%0.2f]",
		# 									res.path_sparse.poses[i].position.x,
		# 									res.path_sparse.poses[i].position.y,
		# 									res.path_sparse.poses[i].position.z)
		# 						breadcrumbWPS.append([res.path_sparse.poses[i].position.x, res.path_sparse.poses[i].position.y, res.path_sparse.poses[i].position.z, 0.0])

		# 					# Display the path
		# 					# print(breadcrumbWPS)
		# 					self.breadcrumbWPS = breadcrumbWPS
		# 					self.display_path(breadcrumbWPS,"/guidance/pathBreadcrum")
		# 					self.breadcrumbMode = True
		# 					self.breadcrumbWPSnextIndex = 0
		# 					self.send_wp(self.breadcrumbWPS[self.breadcrumbWPSnextIndex])
		# 					self.breadcrumbWPSnextIndex +=1 

		# 				else:
		# 					rospy.logerr("solution not found")

		# 			else:
		# 				if self.breadcrumbWPSnextIndex < (len(self.breadcrumbWPS)):
		# 					# We got here a breadcrumb path, we should exuted down here:
		# 					self.send_wp(self.breadcrumbWPS[self.breadcrumbWPSnextIndex])
		# 					# Increment our waypoint counter
		# 					self.breadcrumbWPSnextIndex +=1
		# 				else:
		# 					# If we finish with the breadcrumb waypoints we increase normal waypoints
		# 					self.nextWaypointIndex += 1
		# 					self.breadcrumbMode = False
		# 		else:
		# 			# Else the mission is over, shutdown and quit the node
		# 			# XXX:	This could be used to restart the mission back to the
		# 			#		first waypoint instead to restart the mission
		# 			rospy.loginfo("Mission complete!")
		# 			rospy.signal_shutdown("Complete, Wooh!")
		# 	elif (self.spar_client.get_state() == GoalStatus.PREEMPTED) or (self.spar_client.get_state() == GoalStatus.ABORTED) or (self.spar_client.get_state() == GoalStatus.REJECTED):
		# 		rospy.loginfo("Mission cancelled!")
		# 		rospy.signal_shutdown("cancelled")


		# If we're performing the ROI diversion, then don't do
		# anything here, as this is handled in that function
		if not self.performing_roi:
			# If the last segment has succeeded.
			# For more complex tasks, it might be necessary to also
			# check if you are in waypoint or diversion mode here.
			# Hint: really, we should check for other status states
			#		(such as aborted), as there are some states
			#		where we won't recover from, and should just exit
			if self.spar_client.get_state() == GoalStatus.SUCCEEDED:
				

				# XXX:	Another check could go here to finish the mission early
				#		if "all" inspection tasks have been completed
				#		(Add in another "if" and make the waypoint counter check
				#		 an "elif" check instead.
				#		 i.e. if complete; elif more wps; else wps finished)
				if self.waypoint_counter < (len(self.waypoints)):
					rospy.loginfo("Reached waypoint %i!" % (self.waypoint_counter))
					self.send_wp(self.waypoints[self.waypoint_counter])
					# Increment our waypoint counter
					self.waypoint_counter += 1
					
					# if self.waypoint_counter == (len(self.waypoints)) and self.completed_payload_1 and self.completed_payload_2:
					# 	file=2
				elif not (self.waypoint_counter < (len(self.waypoints))) and not self.land_staging:
					# Check that all waypoints have been completed and the drone has not yet completed the landing staging operation (hovering above landing site)
					#Initiate land_stage
					self.land_stage()
					print("landing at staging area")
					
				elif not (self.waypoint_counter < (len(self.waypoints))) and self.land_staging and not self.landed:
					self.land()
					print("staging complete")

				else:
					# Else the mission is over, shutdown and quit the node
					# XXX:	This could be used to restart the mission back to the
					#		first waypoint instead to restart the mission
					rospy.loginfo("Mission complete!")
					rospy.signal_shutdown("complete")
			elif (self.spar_client.get_state() == GoalStatus.PREEMPTED) or (self.spar_client.get_state() == GoalStatus.ABORTED) or (self.spar_client.get_state() == GoalStatus.REJECTED):
				rospy.loginfo("Mission cancelled!")
				rospy.signal_shutdown("cancelled")

	# Display a path
	def display_path(self, wps, name):
		rospy.loginfo("Displaying path...")
		pub_path = rospy.Publisher(name, Path, queue_size=10, latch=True)
		msg = Path()
		msg.header.frame_id = "/map"
		msg.header.stamp = rospy.Time.now()
	
		for wp in wps:
			pose = PoseStamped()
			pose.pose.position.x = wp[0]
			pose.pose.position.y = wp[1]
			pose.pose.position.z = wp[2]
	
			pose.pose.orientation.w = 1.0
			pose.pose.orientation.x = 0.0
			pose.pose.orientation.y = 0.0
			pose.pose.orientation.z = 0.0
	
			msg.poses.append(pose)
		rospy.loginfo("Publishing path...")
		pub_path.publish(msg)

	def land_stage(self):
		
		#Check that the Aruco landing marker has been discovered, if not set default landing coordinate 0,0
		if np.isnan(self.markers[self.landing_marker,0]) or np.isnan(self.markers[self.landing_marker,1]):
			# Set the landing waypoint at x:0, y:0, z:surveryAltitude, yaw:0
			self.landing_wp = [0,0,self.surveyAltitude, 0] 
			rospy.loginfo("Aruco marker %i not found: using default location [0,0] for landing staging area!" % (self.landing_marker))
		
		#Given that we have a valid coordinate stored in self.markers: Set x y based on selected landing ID
		else:
			self.landing_wp = [self.markers[self.landing_marker,0],self.markers[self.landing_marker,1],self.surveyAltitude,0]
			rospy.loginfo("Landing at Aruco marker %i: location [%i,%i], moving to landing staging area!" % (self.landing_marker, self.landing_wp[0], self.landing_wp[1]))
			
		
		self.land_staging = True
		self.send_wp(self.landing_wp)

	def land(self):
		self.landing_wp = [self.markers[self.landing_marker,0],self.markers[self.landing_marker,1],0,0]
		if not np.isnan(self.markers[self.landing_marker,:]).any():
			rospy.loginfo("Landing at [%i,%i]!" % (self.landing_wp[0], self.landing_wp[1]))
		else:
			rospy.loginfo("Landing at [0,0]!")
		self.landed = True
		self.send_wp(self.landing_wp)
		

def main(args):
	# Initialise ROS
	rospy.init_node('guidance')
	surveyAltitude = rospy.get_param("~surveyAlt", 1)
	# List of waypoints
	surveyAltitude = 1.8
	# [X, Y, Z, Yaw]
	wpsR1 = [[ 0.0, 0.0, surveyAltitude, 0.0],
		   [ 1.0, 1.0, surveyAltitude, 0.0],
		   [-1.0, 1.0, surveyAltitude, 0.0],
		   [-1.0,-1.0, surveyAltitude, 0.0],
		   [ 1.0,-1.0, surveyAltitude, 0.0],
		   [ -1.8, -1.8, surveyAltitude, 0.0]]

	wpsR2 = [[ 0.0, 0.0, surveyAltitude*2, 0.0],
		   [ 1.0, 1.0, surveyAltitude*2, 0.0],
		   [-1.0, 1.0, surveyAltitude*2, 0.0],
		   [-1.0,-1.0, surveyAltitude*2, 0.0],
		   [ 1.3,-1.0, surveyAltitude*2, 0.0],
		   [ 1.3,1.0, surveyAltitude*2, 0.0],
		   [ 1.0,-1.0, surveyAltitude*2, 0.0],
		   [ 0.0, 0.0, surveyAltitude*2, 0.0]]

	if surveyAltitude > 1.5:
		wps = wpsR1
	else:
		wps = wpsR2
	# wps = [[-4.0, 2.5, 1.5, 0.0],    # 1  r1
    #        [-4.0,-2.5, 1.5, 0.0],    # 2  r1
    #        [-2.5,-2.5, 1.5, 0.0],    # 3  r2
    #        [-2.5, 2.5, 1.5, 0.0],    # 4  r2
    #        [-1.5, 2.5, 1.5, 0.0],    # 5  r3
    #        [-1.5,-2.5, 1.5, 0.0],    # 6  r3
    #        [-0.5,-2.5, 1.5, 0.0],    # 7  r4
    #        [-0.5, 2.5, 1.5, 0.0],    # 8  r4
    #        [ 0.5, 2.5, 1.5, 0.0],    # 9  r5
    #        [ 0.5,-2.5, 1.5, 0.0],    # 10 r5
    #        [ 1.5,-2.5, 1.5, 0.0],    # 11 r6
    #        [ 1.5, 2.5, 1.5, 0.0],    # 12 r6
    #        [ 2.5, 2.5, 1.5, 0.0],    # 13 r7
    #        [ 2.5,-2.5, 1.5, 0.0],    # 14 r7
    #        [ 4.0,-2.5, 1.5, 0.0],    # 15 r8
    #        [ 4.0, 2.5, 1.5, 0.0]]    # 16 r8

	# Create our guidance class option
	guide = Guidance(wps, surveyAltitude)

	

	# Spin!
	rospy.spin()


if __name__ == '__main__':
	try:
		main(sys.argv)
	except rospy.ROSInterruptException:
		pass

	print('Node Closed')
